/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ExampleCarousel: typeof import('./components/style/ExampleCarousel.vue')['default']
    FeedbackManager: typeof import('./components/admin/FeedbackManager.vue')['default']
    FeedbackTab: typeof import('./components/profile/FeedbackTab.vue')['default']
    ImageUploader: typeof import('./components/uploader/ImageUploader.vue')['default']
    LoadingSkeleton: typeof import('./components/common/LoadingSkeleton.vue')['default']
    MyPhotosTab: typeof import('./components/profile/MyPhotosTab.vue')['default']
    PhotoFlipbook: typeof import('./components/flipbook/PhotoFlipbook.vue')['default']
    ProfileDialog: typeof import('./components/ProfileDialog.vue')['default']
    ProfileHeader: typeof import('./components/profile/ProfileHeader.vue')['default']
    ProfileInfoTab: typeof import('./components/profile/ProfileInfoTab.vue')['default']
    ProviderSelector: typeof import('./components/style/ProviderSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/SiteFooter.vue')['default']
    SkillManager: typeof import('./components/admin/SkillManager.vue')['default']
    StyleGallery: typeof import('./components/style/StyleGallery.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
